accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.urls import reverse_lazy


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    ExpenseCategoryListView,
    ExpenseCategoryCreateView,
    AccountListView,
    AccountCreateView,
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="receipts_create"),
    path(
        "expense_categories/list/",
        ExpenseCategoryListView.as_view(),
        name="expense_category_list",
    ),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="expense_category_create",
    ),
    path("accounts/list/", AccountListView.as_view(), name="account_list"),
    path(
        "accounts/create/", AccountCreateView.as_view(), name="account_create"
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
# a value we can apply to receipts like "Gas" or "entertainment"
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


# way we paid for it, such as credit card or bank account
class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


# What the app keeps track of for accounting purposes
class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()

    purchaser = models.ForeignKey(
        USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
    )

    category = models.ForeignKey(
        "ExpenseCategory",
        related_name="receipts",
        on_delete=models.CASCADE,
    )

    account = models.ForeignKey(
        "Account",
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True,
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from receipts.models import ExpenseCategory, Account, Receipt


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    # filter data for only the current user
    def get_queryset(self):
        # purchaser is the user property for Receipt model
        # that is related to ForeignKey
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")  # redirect to listview


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "expense_categories/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "expense_categories/create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("expense_category_list")  # redirect to listview


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("account_list")  # redirect to listview

accounts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <title>Receipt Manager</title>
</head>

<body>
    <header>
        <nav>
            <ul class="nav-links">
                {%if user.is_authenticated %}
                <li>
                    <a href="{% url 'home' %}">Receipts</a>
                </li>
                <li>
                    <a href="{% url 'receipts_create' %}">Create Receipt</a>
                </li>
                <li>
                    <a href="{% url 'expense_category_list' %}">Expense Categories</a>
                </li>
                <li>
                    <a href="{% url 'expense_category_create' %}">Create Expense Category</a>
                </li>
                <li>
                    <a href="{% url 'account_list' %}">Account</a>
                </li>
                <li>
                    <a href="{% url 'account_create' %}">Create Account</a>
                </li>
                <li>
                    <a href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'signup' %}">Sign Up</a>
                </li>
                <li>
                    <a href="{% url 'login' %}">Log In</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
</body>

</html>

receipts/templates/accounts/create.html
{% extends 'base.html' %}

{% block content %}
<div class="create-account-form">
    <h1>Create an Account</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="create-acc-button">Create Account</button>
    </form>
</div>
{% endblock content %}

receipts/templates/accounts/list.html
{% extends 'base.html' %}

{% block content %}
<h1>Account</h1>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Number</th>
            <th>Number of receipts</th>
        </tr>
    </thead>
    <tbody>
        {% for acct_info in account_list %}
        <tr>
            <td>{{acct_info.name}}</td>
            <td>{{acct_info.number}}</td>
            <td>{{acct_info.receipts.all|length}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

receipts/templates/expense_categories/create.html
{% extends 'base.html' %}

{% block content %}

<div class="expense-create-form">
    <h1>Create an Expense Category</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="create-expensecat-button">Create Expense Category</button>
    </form>
</div>
{% endblock content %}

receipts/templates/expense_categories/list.html
{% extends 'base.html' %}

{% block content %}
<h1>Expense Categories</h1>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Number of receipts</th>
        </tr>
    </thead>
    <tbody>
        {% for exp_categ in expensecategory_list %}
        <tr>
            <td>{{exp_categ.name}}</td>
            <td>{{exp_categ.receipts.all|length }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}

{% block content %}
<div class="create-receipt-form">
    <h1>Create a Receipt</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="create-receipt-button">Create Receipt</button>
    </form>
</div>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}

{% block content %}
<h1>Receipts</h1>
<table>
    <thead>
        <tr>
            <th>Vendor</th>
            <th>Total</th>
            <th>Tax</th>
            <th>Date</th>
            <th>Category</th>
            <th>Account</th>
        </tr>
    </thead>
    <tbody>
        {% for receipt_info in receipt_list %}
        <tr>
            <td>{{receipt_info.vendor}}</td>
            <td>{{receipt_info.total}}</td>
            <td>{{receipt_info.tax}}</td>
            <td>{{receipt_info.date}}</td>
            <td>{{receipt_info.category}}</td>
            <td>{{receipt_info.account}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}